# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      # Discord.JS updates are ignored due to Discord.JS v11 being the last version to officially support userbots
      - dependency-name: "discord.js"
      # node-fetch updates are ignored due to the devs converting it to an ESM only module as of node-fetch 3.x
      - dependency-name: "node-fetch"